configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


before_build:
  - nuget restore SimpleWebsite/SimpleWebsite.sln

build:
  verbosity: minimal
  publish_wap: true
  project: SimpleWebsite/SimpleWebsite.sln

after_build:
  - cmd SimpleWebsite.zip SimpleWebsite-{build}.zip


deploy:
- provider: S3
  access_key_id:
    secure: 4TC42SnhpgHT/pv8LufCdVYzLq3NBBxqzeaBllDsYqE=
  secret_access_key:
    secure: ztnx6/QhFcn7p41Nco/hiC/ov7OdRbbSlEtiVkK4AJyXdMOP4dAbfkafR1i5pxap
  region: eu-west-1
  bucket: zuto-artefacts-repo
  encrypt: false
